# Generated by Django 5.2.13 on 2026-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(unique=True)),
                ('booking_count', models.IntegerField(default=0)),
            ],
        ),
    ]
